# Generated by Django 4.1 on 2022-08-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("word_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="word", old_name="text", new_name="word",),
    ]
