# Generated by Django 4.1 on 2022-08-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word_app", "0002_rename_text_word_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="avatar_color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="appuser",
            name="avatar_mood",
            field=models.CharField(default="happy", max_length=50),
        ),
    ]
